### ISSUE TITLE
Necessary to keep all 4 ports open or only WEB-UI is fine?

### ISSUE THREAD

**Issue by sonuyos** [linuxserver/docker-rutorrent#178]
Below are the ports suggested to keep open/bypass onto the host.

-p 80 | ruTorrent Web UI
-p 5000 | scgi port
-p 51413 | Bit-torrent port
-p 6881/udp | Bit-torrent port

Is it necessary for to bypass all 4 ports or only WebUI port bypass is enough for normal functionality?

**Comment by V33m** [comment]
You have opened an issue which is for issue reporting. This is not the place to ask questions... Look up Linuxserver discord server if you need any support. What I suggest is that you read up on your question as it is quite common. Lastly, please close the issue.

A hint to answering your question is what is the purpose for each port. When you have figured that out, you should be able to answer your own question. I can help you with the second port, `5000 | scgi port`. The reason for using scgi ports are to allow other resources to execute commands as the user owning the process. Hence, in order for ruTorrent to function and connect to rTorrent, you have to setup a scgi port. Unless you don't want to use ruTorrent and control everything through terminal with rTorrent. If that is the case, you don't need port 80 as well since it is the ruTorrent Web UI.

**Comment by triqster1** [comment]
This image uses the socket by default hence you don't need to open the scgi port. I recommend using a different image, though. This one isn't maintained anymore. Loads of open issues are just being ignored for years.
