### ISSUE TITLE
Enabled Pre-allocation (fallocate syscall)

### ISSUE THREAD

**Issue by onedr0p** [linuxserver/docker-rutorrent#28]
**Pre-allocation**
The rTorrent package in the community repository lacks pre-allocation. Compiling rTorrent with pre-allocation allows files to be allocated before downloading the torrent. The major benefit is that it limits and avoids fragmentation of the filesystem. However, this introduces a delay during the pre-allocation if the filesystem does not support the fallocate syscall natively.

Read more at:
https://wiki.archlinux.org/index.php/RTorrent

Allows to set `system.file_allocate.set = yes` in rtorrent.rc

**Comment by thelamer** [comment]
We install rtorrent from alpine repos as you know. 
This repo is in desperate need of a full time maintainer, currently no one on the team is a heavy user as you can see in the issues maintenance has fallen. 
I cannot fathom that we would start custom compiling rtorrent, and because of that I will be closing this issue.
