### ISSUE TITLE
Save As does not display full folder/file path

### ISSUE THREAD

**Issue by norrkin** [linuxserver/docker-rutorrent#32]
I've noticed that using this image that the Save As path does not display the full folder/file path of a given torrent.

i.e. /downloads/incoming
but I'd expect /downloads/incoming/ubuntu-16.04.1-desktop-amd64.iso under the General tab of the torrent when selected.

Is this a limitation of docker?

**Comment by aptalca** [comment]
That is an rutorrent gui thing, not specific to this container or docker.

I believe rutorrent by default saves the files in a folder that has the same name as the torrent name, but it doesn't display that folder name in the gui. In other words, the save as place shows where that "folder" is going to be. 

If that's bothersome, you can always check the box "Don't add torrent's name to path" while adding a torrent and it will save the files directly in the folder you select as the path.

But if you're referring to the file, it never shows the filename in the "save as" sections because many torrents contain more than one file.

**Comment by norrkin** [comment]
Sorry but you're wrong.

Examples;
My docker instance which is not showing the Save As path correctly - https://www.dropbox.com/s/ujfyvyic6rs74uy/docker_instance.png?dl=0

and my server instance which does show the Save As path - https://www.dropbox.com/s/r525cupexlky514/server_instance.png?dl=0

Can you please explain how this is working for my server instance?

**Comment by j0nnymoe** [comment]
I'll spin this container up over the weekend and see if I get the same issue.

**Comment by norrkin** [comment]
The problem seems to be with the versions of rutorrent.  The docker container is grabbing the latest from GitHub but my server was built using the v3.7 release from BinTray.

Guess something in the rutorrent code was changed :(
