### ISSUE TITLE
Rtorrent Crash - DhtRouter::get_tracker did not actually insert tracker

### ISSUE THREAD

**Issue by JigSawFr** [linuxserver/docker-rutorrent#43]
**After a few hours / minutes of container start, rtorrent crash and is unusable.**

Log Output:
`Caught internal_error: 'DhtRouter::get_tracker did not actually insert tracker.'.`

Can be related to: http://libtorrent-devel.rakshasa.narkive.com/ntOmeUGc/dhtrouter-get-tracker-did-not-actually-insert-tracker-rtorrent-0-8-8
Or: https://archlinuxarm.org/forum/viewtopic.php?f=15&t=5578

Reported by another user on linux server forum: (with a possible working workaround):
https://forum.linuxserver.io/thread-292-post-2197.html#pid2197

Seems to be related to DHT setting.

**Comment by JigSawFr** [comment]
Under test with these values in rtorrent.rc:

```
dht = disable
peer_exchange = no
```

**Comment by JigSawFr** [comment]
Rtorrent seems to be stable now, any crash since these changes.

**Comment by JigSawFr** [comment]
@CHBMB thanks you, i can confirm since these new values, i don't have any more crash occurring :)

**Comment by CHBMB** [comment]
@JigSawFr I can't take any credit, @sparklyballs changed the readme, I just merged his PR.

**Comment by duckfullstop** [comment]
I've just run into this while migrating back to rtorrent after a long hiatus, and I'm not really sure that asking an end user to disable DHT / peer exchange (both of which are important parts of bittorrent, especially for magnet links / public trackers) is an acceptable solution to a problem, even if it is the easy way out. With that being said, the only platforms that seem to have been hitting this crash have been unconventional arches like ARM, so it's incredibly odd to be seeing the same issue on a x86 system.

The only thing I can think is that this is some kind of _recent_ alpine regression caused by something like musl libc, which I'm basing off the fact that [this post](http://libtorrent-devel.rakshasa.narkive.com/ntOmeUGc/dhtrouter-get-tracker-did-not-actually-insert-tracker-rtorrent-0-8-8#post2) wants to push the blame in the direction of the C++ STL / compiler (although it's been reported on glibc distributions including debian, so that's probably a false errand). From what I understand, DHT used to work absolutely fine until recently; so the question is, what's changed upstream at libtorrent / rtorrent to cause it to suddenly start throwing this?

**Comment by sarbian** [comment]
I just had this error after I updated from an older image. DHT is one of the core feature of modern bittorrent. Disabling it is counterproductive...

**Comment by Nottt** [comment]
I'm having the same issue with docker, ubuntu 16.04, after some minutes rutorrent crash. Also I do not think turning off DHT is a solution
