### ISSUE TITLE
Make DHT work again

### ISSUE THREAD

**Issue by infernix** [linuxserver/docker-rutorrent#60]
As described in #43 and #52, leaving DHT enabled causes rtorrent to crash; workaround was provided in #44.

However, DHT is an important feature and should not need to be disabled. The root cause of the crash should be found and fixed instead.

There's more bugs that are tracking this problem: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=864995

**Comment by j0nnymoe** [comment]
This is will get fixed once it has been fixed upstream. Unfortunately it's out of our hands.

**Comment by infernix** [comment]
According to the debian bugreport it's only a matter of compiling with USE_ALIGNED, which can be added to the Dockerfile, correct?

**Comment by sparklyballs** [comment]
no it is not something that can be added to the Dockerfile

it is something that needs to be fixed upstream

**Comment by stevesbrain** [comment]
@infernix rtorrent is being added as a package, rather than by compiling (see [here](https://github.com/linuxserver/docker-rutorrent/blob/master/Dockerfile#L48)). Switching to compiling in the docker image would potentially blow out the size of the image significantly enough to make it not worth the hassle, and adds unnecessary complexity. Once it's been patched upstream, the image will be updated :)

Of course, if you like, fork your own copy and change the Dockerfile to compile it yourself in the mean time!

**Comment by Rast1234** [comment]
Can anyone suggest version of docker image to use in meantime, please?

**Comment by stevesbrain** [comment]
@Rast1234 I don't have experience with any of these, but, a Google search turns up:

- https://hub.docker.com/r/diameter/rtorrent-rutorrent/
- https://github.com/kfei/docktorrent
- https://hub.docker.com/r/yusufali/rtorrent/
- https://hub.docker.com/r/gangefors/rtorrent-rutorrent/
- https://hub.docker.com/r/chamunks/alpine-rtorrent/

But, you may be better off just using a previous tag of the linuxserver/docker-rutorrent one :)

**Comment by Rast1234** [comment]
@stevesbrain thanks, i tried tags of linuxserver/docker-rutorrent but gave up on 72

**Comment by sparklyballs** [comment]
as @j0nnymoe quite rightly says this needs to be fixed upstream

any tags of our container will have the same rtorrent version as it quite long in the tooth

closing this

**Comment by infernix** [comment]
Not sure why you want to close this as it's unresolved; having it open at least keeps this on the radar?

Not in the least because the default config does not disable DHT and therefore causes rtorrent to crash, so if anything, that should be fixed, no?

**Comment by sparklyballs** [comment]
because the issue is beyond our control until a fix is made upstream

**Comment by infernix** [comment]
As of the current release the rtorrent.rc contains a config that is known to crash rtorrent; how is disabling DHT in the config out of your control?

**Comment by sparklyballs** [comment]
that "fix" you linked to involves adding a config.h file (which depending on who you talk to is highly irregular and can interfere with the rest of the configure options) and compiling from source

it's not something we are prepared to do and the "fix" was not suggested as a permanent thing in that link it was a POC 

not to mention that the link specifically dealt with arm anyways so any relevance to the issue here is also spurious at best

**Comment by j0nnymoe** [comment]
We have a note in our readme already stating that if user's are getting issues with DHT, to disable it.
https://github.com/linuxserver/docker-rutorrent/commit/52c7bd4988fe93f7f222fc504b8ba03239ba03cc

**Comment by sparklyballs** [comment]
the config.h file only exists during the configure stage of compiling and forcing changes to it is extremely bad practice because it can and will override potentially important settings that are only generated at compile time with the express purpose of configuring the source

it is not something we would be prepared to entertain as it would probably break more than it would fix

as i have already said it was a proof of concept and was specifically for arm in that context anyways and may have zero relevance here anyways

**Comment by infernix** [comment]
I'm not talking about the compile time change here; i am saying that if it's known to crash rtorrent, disabling DHT should be the default until that's fixed upstream. So instead of specifying in the readme, change the rtorrent.rc [here](https://github.com/linuxserver/docker-rutorrent/blob/master/root/defaults/rtorrent.rc#L23).

**Comment by sparklyballs** [comment]
it doesn't affect everyone, the README will suffice

the option can be changed manually and as it is in a mounted volume it is persistent
