### ISSUE TITLE
Ignoring rtorrent.rc.

### ISSUE THREAD

**Issue by RobinGhost** [linuxserver/docker-rutorrent#88]
I am using Debian 9.
My command line to run the rutorrent container is:
`sudo docker create --name=rutorrent --restart=always -v /opt/rutorrent/config:/config -v /srv/dev-disk-by-id-ata-ST4000VN008-2DR166_ZDH2PWQQ-part1/Downloads:/downloads -e PGID=1000 -e PUID=1000 -e TZ=Europe/London -p 8091:80 -p 5000:5000 -p 5****:5**** -p 6881:6881/udp linuxserver/rutorrent `
I have pulled the lastest version of the container.
Everything seems to be running as it should but for some reason in the log file I am getting an error:

> **1538081613 W Ignoring rtorrent.rc.**
> 1538081613 N rtorrent main: Starting thread.
> 1538081613 N rtorrent scgi: Starting thread.

All the permissions seem correct so I cant under why it read the rtorrent.rc
Anybody got any ideas?

**Comment by kinghrothgar** [comment]
This is because rtorrent is run with `-n -o import=/config/rtorrent/rtorrent.rc` which is how you override rtorrent's default config location of `~/.rtorrent.rc`. It is not ignoring the config found at `/config/rtorrent/rtorrent.rc` in the image, it is just informing you in a badly worded message that it isn't loading `~/.rtorrent.rc`.

**Comment by RobinGhost** [comment]
The only reason, I questioned it, is I added the following at the end of my config file and it is not executing as it should.
```
method.insert = d.get_finished_dir,simple,"cat=/srv/dev-disk-by-id-ata-ST4000VN008-2DR166_ZDH2PWQQ-part1/Downloads/,$d.get_custom1=

method.set_key = event.download.finished,move_complete,"d.set_directory=/srv/dev-disk-by-id-ata-ST4000VN008-2DR166_ZDH2PWQQ-part1/Downloads;execute=mkdir,-p,$d.get_finished_dir=;execute=cp,-rpl,$d.get_base_path=,$d.get_finished_dir=
```

`

**Comment by kinghrothgar** [comment]
Looks like you have open `"` on both of those lines and possibly more errors. Here's a good example of how to move completed torrents to a fix location: https://github.com/rakshasa/rtorrent/wiki/Common-Tasks-in-rTorrent#move-completed-torrents-to-a-fixed-location

**Comment by kinghrothgar** [comment]
Also I assume you're adding the torrents via ruTorrent. Most of the standard move on completion snippets out there won't work for torrents added via ruTorrent because they rely on numbered custom fields and ruTorrent uses all numbered customs for internal things.

I dealt with that issue here https://github.com/rakshasa/rtorrent/issues/781

**Comment by RobinGhost** [comment]
Thanks for your feedback, it's very strange though as although I have only just ventured over to this docker based system, I have built my own system manually for some time and its only since I started experiencing XMLRPC issues I switched in the last week to this docker container, before that my code worked fine, I am not sure why though.

**Comment by kinghrothgar** [comment]
To verify that your config is indeed being read (to rule out it not being mounted incorrectly or something else), you can:
1. Put `print="Config successfully read!"` in your rtorrent.rc
2. Start up the docker container
3. Replace `rutorrent` in this command with whatever you named the container with `--name`: `docker exec -it rutorrent screen -r`
4. See if the debug message printed out in the bottom left of rtorrent. 

Unfortunately rtorrent likes to print lots of stuff to the screen instead of logging it..... very frustrating.

**Comment by RobinGhost** [comment]
When I run: 

> print="Config successfully read!" /opt/rutorrent/config/rtorrent/rtorrent.rc


I am getting the error

```
/opt/rutorrent/config/rtorrent/rtorrent.rc: line 1: syntax error near unexpected token `}'
/opt/rutorrent/config/rtorrent/rtorrent.rc: line 1: `execute = {sh,-c,/usr/bin/php7 /usr/share/webapps/rutorrent/php/initplugins.php abc &}'
```

I am not sure why the only changes I have made to the config file is to add the copy commands tot he bottom of the file.
Thanks again for your assistance.

**Comment by kinghrothgar** [comment]
Please post your complete config file as a gist verbatim if you want help with syntax and link it here. Alternatively you can run the command `cat CONFIG_PATH | curl -F 'gob=<-' gobin.io` and paste the first URL that command returns. Replace CONFIG_PATH with the valid path.

If this is indeed copied from your config just as you added it:
```
print="Config successfully read!" /opt/rutorrent/config/rtorrent/rtorrent.rc
```
You have raw unquoted text (`/opt/rutorrent.....`). That line was supposed to read:
```
print="Config successfully read!"
```

**Comment by RobinGhost** [comment]
Thanks for your support @kinghrothgar, I have now satisfied myself that the config file is being read correctly and problem is that the move statement is not working properly. As a test I installed the docker diameter/rtorrent-rutorrent:latest on my system and added  the  following to the config file 
```
method.insert = d.get_finished_dir,simple,"cat=/downloads/,$d.get_custom1="
method.set_key = event.download.finished,move_complete,"d.set_directory=/downloads;execute=mkdir,-p,$d.get_finished_dir=;execute=cp,-rpl,$d.get_base_path=,$d.get_finished_dir="
```
This worked sucessfully on the test docker and failed on this docker
